<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title><?= htmlspecialchars($htmltitle) ?></title>

    <!-- a simple responsive grid system for the map page -->
    <link rel="stylesheet" href="<?= site_url('application/views/site/grid/css/col.css') ?>" media="all">
    <link rel="stylesheet" href="<?= site_url('application/views/site/grid/css/10cols.css') ?>" media="all">

    <!-- jQuery and jQuery UI -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> 
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/<?= $jqueryui_theme ?>/jquery-ui.css">

    <!-- the wonderful ajaxForm plugin -->
    <script src="http://malsup.github.com/jquery.form.js"></script> 

    <!-- sitewide common CSS -->
    <link rel="stylesheet" href="<?= site_url('application/views/site/header.css') ?>" media="all">
</head>
<body>



<form action="<?= current_url() ?>" method="post">
<div class="section">
    <div class="col span_2_of_10">
        &nbsp;
    </div>
    <div class="col span_8_of_10">
        <h2><?= $htmltitle ?></h2>
    </div>
</div>
<div class="section">
    <div class="col span_2_of_10">
        &nbsp;
    </div>
    <div class="col span_1_of_10 right">
        E-mail address: &nbsp;
    </div>
    <div class="col span_7_of_10">
        <input type="text" name="email" placeholder="email address" size="50" maxlength="50" />
    </div>
</div>
<div class="section">
    <div class="col span_2_of_10">
        &nbsp;
    </div>
    <div class="col span_1_of_10 right">
        &nbsp;
    </div>
    <div class="col span_7_of_10">
        <input type="submit" value="Request Password Change" />
    </div>
</div>
</form>


<div class="section">
    <div class="col span_3_of_10">
        &nbsp;
    </div>
    <div class="col span_7_of_10">
        <br/>
        <a href="<?= site_url('site/login') ?>">Return to login page</a>
        <br/>
    </div>
</div>



<script type="text/javascript">
$(document).ready(function () {
    $('#signupform').ajaxForm(function(responseText,statusText,xhr,$form) { 
        alert(responseText); 
    }); 
});
</script>



</body>
</html>