<p>
    Thank you for your submission to <?= $sitename ?>
    <br/>
    Your submission "<?= $feature->name ?>" submitted <?= $feature->submitted_when  ?> has been Accepted for inclusion.
</p>

<p>
    The site admin has the following comments:
    <div style="white-space:pre-line;">
        <?= message ?>
    </div>
</p>

<p>
    If you have any other questions or need assistance, please contact <?= $admin_name ?> at <?= admin_email ?>
</p>
