<?= $label ?><br/>
<!-- the span holds the data-required attribute; used in index.js for validating that at least one is selected -->
<span <?php if ($required) printf('data-required="%s"', htmlspecialchars($required) ); ?>>
<?php foreach ($options as $optval=>$opttxt) { ?>
    <label><input type="radio" name="<?= $fieldname ?>" value="<?= htmlspecialchars($optval) ?>" /> <?= $opttxt ?></label>
    <br/>
<?php } ?>
</span>
<br/>
