<?= $label ?><br/>
<!-- the span holds the data-required attribute; used in index.js for validating that at least one is selected -->
<span <?php if ($required) printf('data-required="%s"', htmlspecialchars($required) ); ?>>
<?php foreach ($options as $optval=>$opttxt) { ?>
    <label><input type="checkbox" name="<?= $fieldname ?>[]" value="<?= htmlspecialchars($optval) ?>" <?php if ($default===$optval) print "checked"; ?> /> <?= $opttxt ?></label>
    <br/>
<?php } ?>
</span>
<br/>
